import type { Metadata } from "next";
import "./globals.css";
import NewsTicker from "./components/NewsTicker";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NewsTicker />
        <Navbar />
        <div className="w-[80%] mx-auto  ">
          <main>{children} </main>
        </div>
      </body>
    </html>
  );
}
